# Generated by Django 3.2.7 on 2022-04-06 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='imgs/')),
                ('details', models.TextField()),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('Catogory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='newsapp.catogory')),
            ],
        ),
    ]
