# Generated by Django 3.2.7 on 2022-04-09 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_auto_20220407_0138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='details',
            new_name='detail',
        ),
    ]
