# Generated by Django 3.2.7 on 2022-04-09 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_rename_details_news_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catogory',
            old_name='Catogory_image',
            new_name='atogory_image',
        ),
    ]
