# Generated by Django 3.2.7 on 2022-04-09 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0005_rename_catogory_image_catogory_atogory_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catogory',
            old_name='atogory_image',
            new_name='catogory_image',
        ),
    ]
