# Generated by Django 3.2.7 on 2022-04-09 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0007_rename_catogory_news_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catogory',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.RenameField(
            model_name='category',
            old_name='catogory_image',
            new_name='category_image',
        ),
    ]
