# Generated by Django 3.2.7 on 2022-04-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0008_auto_20220409_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='showAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_no', models.FloatField(max_length=255, verbose_name='state_no')),
                ('statecrop_name', models.CharField(max_length=255, verbose_name='crop_name')),
                ('yieldd', models.FloatField(max_length=255, verbose_name='yield')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
