# Generated by Django 3.2.7 on 2022-04-11 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0009_auto_20220411_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='showai',
            old_name='statecrop_name',
            new_name='crop_name',
        ),
    ]
