# Generated by Django 3.2.7 on 2022-04-14 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0010_rename_statecrop_name_showai_crop_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='showai',
            options={'verbose_name_plural': 'ShowAI'},
        ),
    ]
