# Generated by Django 3.2.7 on 2022-04-14 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0011_alter_showai_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='showAI',
        ),
    ]
