# Generated by Django 3.2.7 on 2022-04-14 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='showAI',
            new_name='showCal',
        ),
        migrations.AlterModelOptions(
            name='showcal',
            options={'verbose_name_plural': 'ShowCal'},
        ),
    ]
