# Generated by Django 3.2.7 on 2022-04-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='showCal2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_no', models.FloatField(max_length=255, verbose_name='state_no')),
                ('crop_name', models.CharField(max_length=255, verbose_name='crop_name')),
                ('yieldd', models.FloatField(max_length=255, verbose_name='yield')),
            ],
            options={
                'verbose_name_plural': 'ShowCal',
            },
        ),
    ]
