# Generated by Django 3.2.7 on 2022-04-17 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_showcal2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='showCal2',
        ),
    ]
